import React, { useState } from 'react';
import { Target, TrendingUp, Calendar, Clock, Phone, Mail, ChevronRight, CheckCircle2, UserCheck } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent, CardDescription, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { motion } from 'framer-motion';
import { toast } from 'sonner';

interface CareGap {
  id: string;
  patientName: string;
  gapType: 'overdue_hygiene' | 'incomplete_treatment' | 'unscheduled_followup' | 'insurance_max';
  detail: string;
  value: number;
  priority: 'high' | 'medium' | 'low';
}

const mockCareGaps: CareGap[] = [
  {
    id: '1',
    patientName: 'Sarah Jenkins',
    gapType: 'incomplete_treatment',
    detail: 'Crown prep completed 05/10/2024, seat not scheduled.',
    value: 1250,
    priority: 'high'
  },
  {
    id: '2',
    patientName: 'Michael Chen',
    gapType: 'overdue_hygiene',
    detail: '14 months since last SRP. History of localized periodontitis.',
    value: 450,
    priority: 'high'
  },
  {
    id: '3',
    patientName: 'Elena Rodriguez',
    gapType: 'insurance_max',
    detail: '$1,800 remaining 2024 benefits. Unstarted bridge plan.',
    value: 3200,
    priority: 'medium'
  },
  {
    id: '4',
    patientName: 'Robert Taylor',
    gapType: 'unscheduled_followup',
    detail: 'Post-extraction follow-up needed for socket check.',
    value: 0,
    priority: 'low'
  }
];

const RevenueOpportunityEngine: React.FC = () => {
  const [gaps, setGaps] = useState<CareGap[]>(mockCareGaps);

  const resolveGap = (id: string) => {
    setGaps(prev => prev.filter(g => g.id !== id));
    toast.success('Patient outreach initiated. Task moved to tracking.');
  };

  const getGapIcon = (type: CareGap['gapType']) => {
    switch (type) {
      case 'incomplete_treatment': return <Clock className="w-4 h-4 text-amber-500" />;
      case 'overdue_hygiene': return <Calendar className="w-4 h-4 text-blue-500" />;
      case 'insurance_max': return <TrendingUp className="w-4 h-4 text-emerald-500" />;
      case 'unscheduled_followup': return <UserCheck className="w-4 h-4 text-indigo-500" />;
    }
  };

  const totalValue = gaps.reduce((sum, gap) => sum + gap.value, 0);

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card className="bg-emerald-50 border-emerald-100">
          <CardContent className="pt-6">
            <div className="flex justify-between items-center">
              <div>
                <p className="text-sm text-emerald-700 font-medium">Daily Opportunity</p>
                <h3 className="text-2xl font-bold text-emerald-900">${totalValue.toLocaleString()}</h3>
              </div>
              <div className="p-3 bg-emerald-100 rounded-full">
                <Target className="w-6 h-6 text-emerald-600" />
              </div>
            </div>
          </CardContent>
        </Card>
        
        <Card className="bg-blue-50 border-blue-100">
          <CardContent className="pt-6">
            <div className="flex justify-between items-center">
              <div>
                <p className="text-sm text-blue-700 font-medium">Outreach Ready</p>
                <h3 className="text-2xl font-bold text-blue-900">{gaps.length}</h3>
              </div>
              <div className="p-3 bg-blue-100 rounded-full">
                <Mail className="w-6 h-6 text-blue-600" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-amber-50 border-amber-100">
          <CardContent className="pt-6">
            <div className="flex justify-between items-center">
              <div>
                <p className="text-sm text-amber-700 font-medium">Urgent Care Gaps</p>
                <h3 className="text-2xl font-bold text-amber-900">
                  {gaps.filter(g => g.priority === 'high').length}
                </h3>
              </div>
              <div className="p-3 bg-amber-100 rounded-full">
                <TrendingUp className="w-6 h-6 text-amber-600" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card className="border-slate-200">
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <div>
            <CardTitle className="text-xl">Daily Care Gap Checklist</CardTitle>
            <CardDescription>Generated by Revenue Opportunity Engine</CardDescription>
          </div>
          <Badge variant="outline" className="text-slate-500">
            Auto-refresh: 2h
          </Badge>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {gaps.map((gap, index) => (
              <motion.div 
                key={gap.id}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: index * 0.1 }}
                className="group relative flex items-center justify-between p-4 rounded-xl border border-slate-100 hover:border-primary/20 hover:bg-slate-50/50 transition-all"
              >
                <div className="flex items-start gap-4">
                  <div className={`mt-1 p-2 rounded-lg bg-white shadow-sm border border-slate-100`}>
                    {getGapIcon(gap.gapType)}
                  </div>
                  <div>
                    <h4 className="font-semibold text-slate-800 flex items-center gap-2">
                      {gap.patientName}
                      {gap.priority === 'high' && (
                        <span className="w-2 h-2 rounded-full bg-red-500 animate-pulse" />
                      )}
                    </h4>
                    <p className="text-sm text-slate-600">{gap.detail}</p>
                    <div className="flex items-center gap-3 mt-2">
                      {gap.value > 0 && (
                        <span className="text-[10px] font-bold text-emerald-600 bg-emerald-50 px-1.5 py-0.5 rounded uppercase">
                          Est. Value: ${gap.value}
                        </span>
                      )}
                      <span className="text-[10px] font-medium text-slate-400 uppercase">
                        {gap.gapType.replace('_', ' ')}
                      </span>
                    </div>
                  </div>
                </div>
                <div className="flex gap-2">
                  <Button 
                    variant="ghost" 
                    size="icon" 
                    className="h-8 w-8 rounded-full hover:bg-white hover:text-blue-600"
                    onClick={() => toast.info(`Calling ${gap.patientName}...`)}
                  >
                    <Phone className="w-4 h-4" />
                  </Button>
                  <Button 
                    variant="ghost" 
                    size="icon" 
                    className="h-8 w-8 rounded-full hover:bg-white hover:text-primary"
                  >
                    <Mail className="w-4 h-4" />
                  </Button>
                  <Button 
                    variant="ghost" 
                    size="icon" 
                    className="h-8 w-8 rounded-full hover:bg-emerald-50 hover:text-emerald-600"
                    onClick={() => resolveGap(gap.id)}
                  >
                    <CheckCircle2 className="w-4 h-4" />
                  </Button>
                </div>
              </motion.div>
            ))}
          </div>
        </CardContent>
        <CardFooter className="bg-slate-50 border-t justify-center py-3">
          <Button variant="link" className="text-slate-500 text-xs">
            View Full Revenue Analytics <ChevronRight className="w-3 h-3 ml-1" />
          </Button>
        </CardFooter>
      </Card>
    </div>
  );
};

export default RevenueOpportunityEngine;