import { Specialty, FullProcedure } from './types';

export const SPECIALTIES: Specialty[] = [
  { id: 's1', name: 'Orthodontics', code: 'ORTHO', is_active: true },
  { id: 's2', name: 'Endodontics', code: 'ENDO', is_active: true },
  { id: 's3', name: 'Prosthodontics', code: 'PROSTHO', is_active: true },
  { id: 's4', name: 'Periodontics', code: 'PERIO', is_active: true },
  { id: 's5', name: 'Oral Surgery', code: 'OS', is_active: true },
  { id: 's6', name: 'Pedodontics', code: 'PEDO', is_active: true },
  { id: 's7', name: 'Oral Medicine', code: 'OM', is_active: true },
  { id: 's8', name: 'General Dentistry', code: 'GEN', is_active: true },
];

export const MOCK_PROCEDURES: FullProcedure[] = [
  {
    id: 'p1',
    patient_id: '123',
    tooth_number: 19,
    tooth_system: 'Universal',
    procedure_code: 'D3330',
    procedure_description: 'Root canal therapy, molar',
    primary_specialty_id: 's2',
    primary_specialty: SPECIALTIES[1],
    procedure_date: '2026-03-20',
    provider_id: 'prov1',
    provider_name: 'Dr. Sarah Smith',
    fee: 1200,
    notes: 'Patient reported sensitivity to cold. Necrotic pulp confirmed.',
    is_archived: false,
    created_at: '2026-03-20T10:00:00Z',
    specialty_data: {
      number_of_canals: 4,
      working_length: 21.5,
      obturation_material: 'Gutta-percha',
      sealer: 'AH Plus',
      file_system: 'WaveOne Gold',
      symptoms_before: 'necrotic',
      is_retreat: false,
    },
  },
  {
    id: 'p2',
    patient_id: '123',
    tooth_number: 8,
    tooth_system: 'Universal',
    procedure_code: 'D6010',
    procedure_description: 'Implant Placement',
    primary_specialty_id: 's5',
    primary_specialty: SPECIALTIES[4],
    secondary_specialty_ids: ['s3'],
    secondary_specialties: [SPECIALTIES[2]],
    procedure_date: '2026-02-15',
    provider_id: 'prov2',
    provider_name: 'Dr. James Miller',
    fee: 2500,
    notes: 'Successful implant placement at site #8.',
    is_archived: false,
    created_at: '2026-02-15T09:00:00Z',
    specialty_data: {
      surgery_type: 'Implant Placement',
      reason: 'Missing tooth',
      anesthesia: 'Local + IV Sedation',
      follow_up_date: '2026-03-01',
    },
  },
  {
    id: 'p3',
    patient_id: '123',
    tooth_system: 'Universal',
    procedure_code: 'D8080',
    procedure_description: 'Comprehensive Orthodontic Treatment',
    primary_specialty_id: 's1',
    primary_specialty: SPECIALTIES[0],
    procedure_date: '2026-01-10',
    provider_id: 'prov3',
    provider_name: 'Dr. Elena Vance',
    fee: 5500,
    notes: 'Starting active phase.',
    is_archived: false,
    created_at: '2026-01-10T14:00:00Z',
    specialty_data: {
      malocclusion_class: 'II',
      appliance_type: 'Fixed Ceramic Braces',
      archwire_size: '0.16 Niti',
      elastics_preset: 'Class II patterns',
      treatment_phase: 'Active',
      retention_appliance: 'None yet',
    },
  },
  {
    id: 'p4',
    patient_id: '123',
    tooth_number: 14,
    tooth_system: 'Universal',
    procedure_code: 'D4341',
    procedure_description: 'Periodontal Scaling and Root Planing',
    primary_specialty_id: 's4',
    primary_specialty: SPECIALTIES[3],
    procedure_date: '2025-12-05',
    provider_id: 'prov4',
    provider_name: 'Dr. Robert Brown',
    fee: 450,
    notes: 'Localized SRP on UR quadrant.',
    is_archived: false,
    created_at: '2025-12-05T11:00:00Z',
    specialty_data: {
      procedure_subtype: 'Root Planing',
      sites_involved: [14, 15],
      membrane_used: false,
    },
  },
];